#.travis.yml

language: node_js
node_js:
  - "8.11.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run test -- --single-run --no-progress --browser=ChromeHeadlessCI
  - npm run e2e -- --no-progress --config=protractor-ci.conf.js
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: pedherlop@gmail.com
    on_success: pedherlop@gmail.com